### ISSUE TITLE
Active icon not switching to green

### ISSUE THREAD

**Issue by markkimsal** [dallenwilson/gstm#1]
Thanks so much for updating gSTM.

When I start a tunnel, the start button becomes insensitive, but the red icon next to the name does not switch to green.

I put some breakpoints in fniface.c near anything that mentions "red.xpm" and "green.xpm" but they don't hit.

**Comment by dallenwilson** [comment]
Thanks for the report, I will have a look.

**Comment by dallenwilson** [comment]
I found and fixed a glaringly obvious error I missed during my testing. Try a build from the new bugfix branch.

**Comment by dallenwilson** [comment]
I apologize for this getting closed before you got a chance to confirm it was fixed; I merged the bugfix branch in to master and github detected the commit that referenced the issue and automagically closed it. It's just helpful that way, I guess.

There is a new release available that includes the fix, as well as packages for Ubuntu/Debian/Mint and Gentoo. Or you can build from the master branch and try it out.
