### ISSUE TITLE
 The repository 'http://ppa.launchpad.net/dallen.wilson/ppa/ubuntu groovy Release' does not have a Release file.

### ISSUE THREAD

**Issue by AirHeadsbuirse** [dallenwilson/gstm#15]
Hello! Any idea whether this will work with kali? I am getting the following error, assumingly because you don't have release notes for Kali..

**Comment by dallenwilson** [comment]
Should work now. Give it another try.

**Comment by AirHeadsbuirse** [comment]
I appreciate the response, i am having a problem with the public key when trying to do apt-get update. Ive tried adding --allow-unauthenticated to no avail.


`Err:5 http://ppa.launchpad.net/dallen.wilson/ppa/ubuntu groovy InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2603163EE5C15AFC
Reading package lists... Done
W: GPG error: http://ppa.launchpad.net/dallen.wilson/ppa/ubuntu groovy InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 2603163EE5C15AFC
E: The repository 'http://ppa.launchpad.net/dallen.wilson/ppa/ubuntu groovy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
`

`Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux
`

**Comment by dallenwilson** [comment]
It looks like your system is missing the public key for the repository.

How did you add the ppa? I'm unfamiliar with Kali and what repo management methods it may or may not support. Most Debian/Ubuntu/Mint users use a wrapper to add ppa's (add-apt-repository), though it can also be done by directly adding the url to `/etc/apt/sources.list`. The 'old fashioned way', as they say.

If you used add-apt-repository, then the key should have been fetched automatically. Check your keyring to see if it's there: `gpg --list-keys | grep --color=always -e "^" -e "2603163EE5C15AFC"`
If you added the url yourself, you'll need to manually fetch the key and add it to your ring. Something like this: `sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 2603163EE5C15AFC` should do the trick.

**Comment by dallenwilson** [comment]
I'll assume you got things sorted out. If not, feel free to re-open.
