### ISSUE TITLE
Cannot specify local IP address for tunnel

### ISSUE THREAD

**Issue by t-oster** [dallenwilson/gstm#16]
Hi,

I need to create a tunnel like `-L127.0.0.3:12345:remotehost:12345`, but there is no field for `127.0.0.3`. I am using the same local port simultaneously on many tunnels and use the local IP addresses 127.0.0.X to differenciate between them.

It is possible to add this field?

**Comment by dallenwilson** [comment]
Quite possible. I'll set some time aside this weekend. In the meantime, if you hand-edit the gstm.ui file to increase the allowed length and allow non-numeric input of the local port field, you should be able to squeeze '127.x.x.x:' in front of your local port. Based on a quick glance at how gstm passes it's arguments to ssh, I think that would work.

**Comment by t-oster** [comment]
Thanks for the quick answer, will check on Tuesday

**Comment by dallenwilson** [comment]
I pushed branch 'localip' with support for specifying an IP when setting up a local tunnel, defaulting to `127.0.0.1:`. I shoe-horned it in to the local port field as described in the potential work-around above, to avoid potential issues from changing the config file layout. Let me know if it meets your requirements.

**Comment by t-oster** [comment]
Hi,
that works like a charm. Thanks for the quick fix.
