### ISSUE TITLE
Broken tray icon under Fedora 32 with TopIconsPlus

### ISSUE THREAD

**Issue by reanimus** [dallenwilson/gstm#18]
I'm not able to see any tray icons when I open gSTM, even when I tried fiddling around with other extensions and stuff. Pidgin is able to successfully use the tray, so I'm not entirely sure *why* it's not working.

As a workaround, I sort of finished implementing appindicator support here:https://github.com/reanimus/gstm/commit/2ac94a9fd85ad7a405148b1d3043b35a5d9c6383

It does away with the old-style tray icon entirely, though, and adds libappindicator as a dependency. I only updated the RPM packaging bits cause that's what I use.

**Comment by dallenwilson** [comment]
It may be as late as November before I can take a look and merge it, but I will get to it. Thanks for the work, I've been wondering what to do with the tray icon since I ported it to gtk3.

**Comment by dallenwilson** [comment]
Looks good to me. And you're half-right about icons not being supported. I fooled around with libappindicator support for a while before going with the GtkStatusIcon, and while I did manage to get icons displayed like the old tray icon menu, they left quite a large blank space / margin in the menu, making it look.. not good.

I'll see what I can accomplish with StatusNotifierItem.

**Comment by dallenwilson** [comment]
@reanimus Try a build from the ui-improvement branch and let me know if it meets your needs. I built on your work and changed the menu creation code a bit to get the images back without using any depreciated gtk functions.

**Comment by dallenwilson** [comment]
Scratch that, the images in the AppIndicator tray menu don't show up on under Cinnamon's tray, but they do under xfce4. Strange. I'll ping you again once I get that figured out.

Edit: Cinnamon has settings under Themes that override application-level settings. Turning on 'show icons in menus' and 'show icons on buttons' magically fixed the issue. So, carry on and give it a try.

**Comment by reanimus** [comment]
Not sure if yours has this bug, but the patch I posted also has an issue where the AppIndicator menu doesn't properly update on error/disconnect (the menu item is still "Disconnect from <X>")

edit: just saw the addition, I'll give it a spin

**Comment by reanimus** [comment]
> Scratch that, the images in the AppIndicator tray menu don't show up on under Cinnamon's tray, but they do under xfce4. Strange. I'll ping you again once I get that figured out.
> 
> Edit: Cinnamon has settings under Themes that override application-level settings. Turning on 'show icons in menus' and 'show icons on buttons' magically fixed the issue. So, carry on and give it a try.

I use GNOME, which seems to not be showing any of the menu icons? At least not with any of the appindicator extensions I tried.

**Comment by reanimus** [comment]
![image](https://user-images.githubusercontent.com/1053912/99630652-233c2980-29ef-11eb-993e-8ae114d5cb8c.png)
That's what it looks like on my system.

Also worth noting: the menu should refresh when you add/remove entries. I don't believe it does now.

**Comment by reanimus** [comment]
(It's definitely not a bug with gnome/the extension, as I just downloaded an [old keyboard status appindicator applet](https://launchpad.net/indicator-keylock) and ran it, and it resulted in a valid menu with some images, though some of them are the missing icon)
![image](https://user-images.githubusercontent.com/1053912/99632437-11a85100-29f2-11eb-9ea4-cf990a59b793.png)

**Comment by dallenwilson** [comment]
Have a look at https://askubuntu.com/a/1095738 and see what happens.

**Comment by reanimus** [comment]
Both result in 'no such key' errors. I tried `gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ButtonImages': <1>, 'Gtk/MenuImages': <1>}"` but that also results in the same menu.

Worth noting that the indicator plugin for the keys I screenshotted above has menu images without me doing anything extra. I think it may have something to do with the construction of the menu? Not sure.

**Comment by reanimus** [comment]
Alright, I used lxappearance to set these settings (they have to be set via the GTK3 settings.ini). Now it's working!

![image](https://user-images.githubusercontent.com/1053912/99709240-c6bf2580-2a53-11eb-9d17-ffb76c962b9d.png)

The connect/disconnect icons aren't made for dark themes I think, but that's an icon issue. Otherwise seems to be good. :)

**Comment by reanimus** [comment]
Overall, this implementation seems to work mostly correctly, but I noted two bugs:

1. Adding/removing a connection doesn't update the app indicator menu list
2. Connecting via the main window also does not update the indicator menu

Issue 1 can result in a crash (remove a server entry, try to connect/disconnect from it in the indicator menu)

**Comment by dallenwilson** [comment]
I'll address both those issues shortly. Thank you for noting them.

All icons and images are from the original project, circa 2005. They could all use updating, so thanks for the PR on that as well.

So, it seems that whether menu icons display or not is going to vary from system to system, thanks to how gtk handles system-level settings vs the application defaults. And the system-level default, from our sample size of two, is apparently "no icons". I'm not a big fan of dealing with support and issues for things that aren't the applications fault, so I'm leaning towards either removing the icons from the docklet menu, or keeping them but expanding the text labels to make them redundant. Attempting to override the system setting and force them to display may be a third option, but I do not like it.

What do you think?

**Comment by reanimus** [comment]
I had my implementation expand the labels, and I think that's fair. Something as simple as Start/Stop <NAME> or Connect/Disconnect <NAME> gets it across well. The icons are still useful for quickly differentiating them, though. That's why I opted for newer graphics in my PR rather than switching to some of the built-in icons (as their visual distinctiveness varies by icon theme), and I'd lean toward keeping them in.

**Comment by dallenwilson** [comment]
New commit pushed, text re-added, copyrights updated, and the two issues with the menu not updating have been addressed.

I remember now why I passed on AppIndicator when I migrated this application to gtk3. Not getting any signals or callbacks when the indicator gets clicked or the menu opens just... irks me.

**Comment by dallenwilson** [comment]
I merged the ui-improvements branch in to the more general devel branch, in prep for the next release. Give it a try and open another issue if you find anything broken. There's bound to be something.
