### ISSUE TITLE
[BUG] Error windows never close

### ISSUE THREAD

**Issue by kero99** [dallenwilson/gstm#2]
Hello, firsts of all, thanks you soo much for this GTK3 implementation, i use this program every day and you help me in my recent upgrade to Mint 19.1 MATE =).

One of the most important bug in this implementation is that when a error happen, a message in a "Untitled window" appear and this message can't be closed, if you press OK button or try to close, the message appear again =(.

I always need to do a pkill to close the program.

Best regards.

**Comment by dallenwilson** [comment]
I have not been able to reproduce anything like this. Can you provide more detail, or specific steps to reproduce the bug?

I'll find time to set up a VM with Mint MATE to see if that helps me track it down. I've tested it with xfce4 and Cinnamon, but not Mate or other DE's.

**Comment by kero99** [comment]
Yes, reproduce the bug is very easy. Every error windows that appear is impossible to close and you need to kill the program. For example a connection timeout or closed tunnel errors, you can see the error windows but if you try to close the error window, the window appear again.
I install the program via your ppa repo.

I can try to compile from code if you want

**Comment by kero99** [comment]
Is like this:
![screenshot1](https://user-images.githubusercontent.com/143736/54284285-f5f37300-459f-11e9-9a42-2e06e781c90b.png)
Now i need kill gstm because this window never close and lock interface.

**Comment by dallenwilson** [comment]
Thank you for the information. On every machine I have tested on, that window does close, and the interface does not lock, and the program does not need to be killed. So let us try to discover why this happens for you. I will start by getting a copy of Mint 19.1 MATE and installing gstm from the ppa, and go from there.

**Comment by kero99** [comment]
Thanks you very much =)

**Comment by dallenwilson** [comment]
I managed to re-produce the behaviour on Mint 19.1 MATE 32-bit, and 64-bit. I've tested a fix on both and it seems to work, please checkout the mintmate branch and try building and testing it on your machine.

**Comment by kero99** [comment]
Yesssssss!!! Is working now!!!!!
Thanks you very much =)

**Comment by kero99** [comment]
Fixed
