### ISSUE TITLE
gstm taking 100% CPU

### ISSUE THREAD

**Issue by mrspirytus** [dallenwilson/gstm#20]
Today I installed the latest version from your PPA on ubuntu 20.04. After configuring it and connecting, I have 5 tunnels running. gSTM is running for about 7-8 hours or so. I initially connected to remote servers using created tunnels. Then I closed all my ssh tunneled connections. I mean I left gSTM running and connected. Just a few min ago I noticed that my CPU is very high. I can see in htop, that it is gSTM who is using near 100%. Not sure when this started. But again I left gSTM connected but I did not connect any ssh session for over 6 hr. Please see the screenshot. As you can see I have 5 forwards setup. One of them is going crazy.
Let me know if there is any extra info you need next time this happens.

![image](https://user-images.githubusercontent.com/60390416/99033871-7de20b00-2541-11eb-918d-f6d5ebe18cde.png)

**Comment by mrspirytus** [comment]
So I did try to disconnect and UI is showing that it is disconnected but process is still hanging around. Well one gstm exited out of 5. I will leave it running over night just in case you need some info about it while I have it. Have you noticed anything like that yourself?

![image](https://user-images.githubusercontent.com/60390416/99034389-a585a300-2542-11eb-8fcc-347ee03cf130.png)

**Comment by xvybihal** [comment]
I use gstm very often, and I have never experienced/noticed this. I sometimes leave it hanging in tray for days. Sometimes even with running tunnels that  forgot to shut down. And I did not notice any CPU spikes. I use Arch btw.

**Comment by mrspirytus** [comment]
I just looked it and nothing changed since last screen shot. Any idea how and where yo look for?
Looks like kill -9 is only option now

![image](https://user-images.githubusercontent.com/60390416/99095539-ddb8d000-259a-11eb-8e2b-df8d0e714216.png)

**Comment by mrspirytus** [comment]
Ok something is seriously wrong :) So I killed gstm, `ps -ef | grep -i gstm` did not show anything. But `netstat -an -t -l` is showing tunnel still active. So I `ps -ef | grep ssh` and sure enough I see ssh with all `-L` forwards listed. Now I started gstm and it I see that my configured session is had red icon as not connected. I did grep for ssh and same as above. So I clicked connect. Now greping for ssh I see two identical lines. No errors from gstm. netstat still shows 5 forwards. I am not sure how there could be two ssh separate forwards running and opening same 5 forwards with out error. Please see attaches screen shot.
![image](https://user-images.githubusercontent.com/60390416/99097236-f5915380-259c-11eb-9b1a-e0022cc5962b.png)

So looks like killing gstm with -9 does not kills the child processes? So for above example I killed gstm and not I have tow `ssh -L...` running

**Comment by dallenwilson** [comment]
`kill -9 gstm` will explicitly Not kill any tunnels. Gstm launches  ssh with g_thread_new(), not fork(), making them independent. I assume this was a deliberate choice on the part of the original programmer back in 2003. If he ever reappears, we can ask him.

As to your problem, I've never heard of it happening before. Does it happen every time you leave it running for a few days? Can it happen with any tunnel, or only specific ones? Can you artificially interfere with the ssh connection somehow and reproduce it on-demand?

**Comment by mrspirytus** [comment]
To tell you the truth, this happened to me on very first try after installing it. So far I did not have issue. But I leave tunnels open for days. I will keep watching.

**Comment by dallenwilson** [comment]
If you find a way to reproduce the problem consistently, feel free to provide a gdb trace.
