### ISSUE TITLE
Autostart tunnel will block the display of GUI

### ISSUE THREAD

**Issue by richardfat7** [dallenwilson/gstm#25]
I create a new tunnel and tick auto-start, save and close the GUI. When I call gSTM next time by clicking icon/command line, it will just connect to the tunnel and never show the GUI again (which i cannot add more tunnel). It will be better if the GUI still show up even if there are auto start tunnels.

**Comment by dallenwilson** [comment]
If you set up a tunnel to auto-start at launch, gSTM will start minimized to the system tray. The gui can be shown/hidden by using the tray icon menu.

If you don't see the tray icon, make sure your desktop environment supports libappindicator status icons. If gSTM doesn't detect libappindicator support it should always show the main gui, but that snippet of code may need some more testing.

**Comment by dallenwilson** [comment]
No follow-up from user, closing.
