### ISSUE TITLE
Move config directory to `~/.config/gstm`

### ISSUE THREAD

**Issue by IStranger** [dallenwilson/gstm#26]
Thanks for the great tool!
It would be great to move config directory to `~/.config/gstm` place (as with most modern programs). 

For example: this directory maybe created only for new installations. And old config dir `~/.gSTM` maybe used for the existing installations (for backward compatibility).

**Comment by dallenwilson** [comment]
It's a reasonable proposal. gSTM may predate the XDG Base Directory specification, they were both released around the same era.

As features go, it's not a very high priority for me. If I get a lucky combination of free time and ambition, I'll implement it.

I'm leaving the issue open to remind myself, if that combination ever occurs.

**Comment by dallenwilson** [comment]
I've made the change, under branch newConfLoc. Give it a try and see if you can cause it to break somehow.

gSTM will check for the old location, and migrate any configured tunnels it finds to the new location. Afterwards, it will not touch the old location again, not even to remove it.

**Comment by dallenwilson** [comment]
We'll assume it all worked beautifully. There will be a new release Real Soon Now (tm) which will include this change.
