### ISSUE TITLE
Ubuntu 22.04 LTS release

### ISSUE THREAD

**Issue by Schnoop** [dallenwilson/gstm#30]
Hi,

i just want to let you know that on 21th of april a new Ubuntu LTS version will be released. As you've written in your readme you are not monitoring new Ubuntu releases and would like to have a ticket to let you know.

I would be very thankful if you would create a release on your launchpad ppa when the time has come.

Thanks for your time and work! I really appreciate.

**Comment by dallenwilson** [comment]
Downloading the ISO now, we'll see what happens. Thanks for the heads up.

**Comment by dallenwilson** [comment]
Packages are now available for "Impish" and "Jimmy" (whatever those work out to in real version numbers), and I've verified that the source does compile and run on 22.04.

Beyond that, you're on your own :) Have fun!

**Comment by zhang8473** [comment]
The source does not compile on 22.04.
```
configure: error: Package requirements (appindicator3-0.1) were not met:

No package 'appindicator3-0.1' found
```
> sudo apt-get install libappindicator3-dev
`libayatana-appindicator3-1 : Conflicts: libappindicator3-1`
