### ISSUE TITLE
The source does not compile on Ubuntu 22.04.

### ISSUE THREAD

**Issue by zhang8473** [dallenwilson/gstm#32]
```
configure: error: Package requirements (appindicator3-0.1) were not met:

No package 'appindicator3-0.1' found
```
> sudo apt-get install libappindicator3-dev
`libayatana-appindicator3-1 : Conflicts: libappindicator3-1`

**Comment by zhang8473** [comment]
To solve the problem in 1.3.7:
1. systray.c & systray.h 
`#include <libayatana-appindicator/app-indicator.h>`
2. configure.ac
`PKG_CHECK_MODULES(APPINDICATOR, [ayatana-appindicator3-0.1])`
3. Change compile command from
`gcc -Wall -g -Og -ggdb...-Wl,  -export-dynamic`
to `gcc -Wall -g -Og -ggdb...-W  -export-dynamic` to fix the `/usr/bin/ld not found` error
Finally, it got compiled

**Comment by dallenwilson** [comment]
Yes, I know. Most distributions have made the switch from libappindicator to libayatana-appindicator, and are finally dropping the legacy libappindicator packages.

The distribution I do my development on (Gentoo) has not completed the switch yet. Once it does, I'll be patching gSTM accordingly and pushing a new release.

I don't have a timeline on that, it will happen when it happens. I'll leave this issue open until then.

**Comment by dallenwilson** [comment]
I just pushed a commit adding libayatana-appindicator support. Let me know if there are any issues, I tested it against both libayatana-appindicator and libappindicator and it seems to be happy with either.
