### ISSUE TITLE
Consider adding "reconnect all tunnels" menu option

### ISSUE THREAD

**Issue by ei8fdb** [dallenwilson/gstm#33]
Firstly thanks for gstm (and particularly making it available on modern GTK versions).

**Request**
Consider adding a "reconnect all tunnels" menu in the GNOME toolbar/menu.

**Context**
I use a number of SSH tunnels configured on my laptop. Sometimes (actually quiet often) I need to reconnect all tunnels, usually as a result of network wonky-ness (network not recovering correctly - after hibernation/sleep, after changing network). Usually this network wonky-ness is beyond a users control or ability to fix.

**Work-around**
At the moment in order to fix this, I need to quit gstm, then reopen it. Then all tunnels will restart automatically. 

**Suggested improvement**
If there was a "Reconnect all" option this would save small but annoying step.

**Alternative improvement**
Obviously, the ideal solution would be for the tunnels to automatically reconnect themselves, but I've yet to see this happen successfully 100% of the time! If there is a way to make this happen, I'd be very happy to know. :)

**Suggested design**
![Screenshot from 2022-08-26 16-27-50](https://user-images.githubusercontent.com/1899506/186926943-6bc000ee-6b65-42a1-a281-f4e349028793.png)

[You can see the design in more detail on [the Penpot UI wireframes](https://design.penpot.app/#/view/e66efa70-2544-11ed-9977-c67f7655c7b3?page-id=e66efa71-2544-11ed-9977-c67f7655c7b3&section=interactions&index=0&share-id=1232afc0-254b-11ed-9977-c67f7655c7b3)]

**Comment by dallenwilson** [comment]
There is an option configured per-tunnel, to re-start the tunnel if it disconnects or fails. As gSTM is just a front-end to ssh, it relies on ssh to notice a tunnel is disconnected.

Does that feature not work when you suffer from your network-wonkyness?

The only reconnect-all implementation I can think off offhand would involve trying to close every configured tunnel if it's marked active, and then re-starting each tunnel after a suitable wait period. Would that be an acceptable solution?

**Comment by subtervisor** [comment]
This is a pretty common issue with long-lived SSH tunnels that are interrupted by sleep or some other event like that. What's essentially happening is this:

1) You connect to the server, TCP handshake happens, everything is golden. SSH session is running.
2) You sleep your computer. As it's suspended, it stops responding to TCP ACKs on its end. TCP has a very large timeout, so at the app layer, it seems like your computer is just taking a long time from the server's perspective.
3) The server either has TCP time out waiting for your response, or it attempts to send keepalive packets to your machine, but never gets the response for them. After enough time, the server will close its side of the connection.
4) Your computer wakes up. From ssh's point of view, the socket is still open and active, but the server stopped listening to that connection long ago. Crucially, though, your client doesn't know that, and it'll go through the same waiting period that the server did.
5) Your client will wait to hear back from the server (how long depends on your TCP/SSH timeout settings), then eventually disconnect after one of the timeouts elapses.

The most straightforward way to fix this, imo, is using the ServerAliveInterval and ServerAliveCountMax settings to set up client-side keep alives. That way, your laptop will proactively send a ping over the SSH tunnel every N seconds, and if a certain number of pings fails, will terminate the connection (allowing gSTM to restart it for you).

**Comment by dallenwilson** [comment]
That's a good solution. gSTM is no replacement for a properly configured ssh installation, and knowing how to use `~/.ssh/config` is definitely part of a properly configured ssh installation.

Thanks.
