### ISSUE TITLE
Building from a release tarball | Failed

### ISSUE THREAD

**Issue by Ricky-Tigg** [dallenwilson/gstm#35]
For Fedora | Relevant packages installed
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version} | %{summary}' automake pkgconf gtk3 glib2 libxml2 libappindicator gcc intltool gtk+
automake 1.16.5 | A GNU tool for automatically creating Makefiles
gcc 12.2.1 | Various compilers (C, C++, Objective-C, ...)
glib2 2.74.1 | A library of handy utility functions
gtk+ 1.2.10 | The GIMP ToolKit
gtk3 3.24.35 | GTK+ graphical user interface library
intltool 0.51.0 | Utility for internationalizing various kinds of data files
libappindicator 12.10.1 | Application indicators library
libxml2 2.10.3 | Library providing XML and HTML support
pkgconf 1.8.0 | Package compiler and linker metadata toolkit
```
Hello. As you may have not noticed, as the result of my investigations the non-correct names of the packages mentioned as part of the[ instructions](https://github.com/dallenwilson/gstm#building-from-source) were here rectified.

Package equirements are met, ready to proceed. It fails.
```
$ ./autogen.sh && ./configure && make
configure.ac:23: warning: macro 'AM_GLIB_GNU_GETTEXT' not found in library
intltoolize: 'po/Makefile.in.in' exists: use '--force' to overwrite
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking whether NLS is requested... yes
checking for intltool >= 0.35.0... 0.51.0 found
checking for intltool-update... /usr/bin/intltool-update
checking for intltool-merge... /usr/bin/intltool-merge
checking for intltool-extract... /usr/bin/intltool-extract
checking for xgettext... /usr/bin/xgettext
checking for msgmerge... /usr/bin/msgmerge
checking for msgfmt... /usr/bin/msgfmt
checking for gmsgfmt... /usr/bin/msgfmt
checking for perl... /usr/bin/perl
checking for perl >= 5.8.1... 5.36.0
checking for XML::Parser... ok
./configure: line 4782: AM_GLIB_GNU_GETTEXT: command not found
./configure: line 4784: LT_INIT: command not found
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GTK3... no
configure: error: Package requirements (gtk+-3.0 >= 3.22) were not met:

Package 'gtk+-3.0', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you installed software in a non-standard prefix.

Alternatively, you may set the environment variables GTK3_CFLAGS and GTK3_LIBS to avoid the need to call pkg-config
```
- `checking for GTK3... no` | Despite GTK3 is **attested installed**
- `Package requirements (gtk+-3.0 >= 3.22) were not met:` | Despite version reportedis **3.24**
- `Package 'gtk+-3.0', required by 'virtual:world', not found` | Then the non-found correct path to binary _gtk+_ is the root of this issue.
- `Consider adjusting the PKG_CONFIG_PATH (...)` and `Alternatively, you may set the environment (...)` | I would not known how to interpret correctly those statements.

**Comment by dallenwilson** [comment]
>Hello. As you may have not noticed, as the result of my investigations the non-correct names of the packages mentioned as part of the[ instructions](https://github.com/dallenwilson/gstm#building-from-source) were here rectified.

The dependencies listed are not package names, they are library names. Every distribution names their packages a little differently, and there is some expectation that an end user building something from a source tarball will 'figure it out', as you did.

> Building from Source
>
> If you're building from a release tarball, you'll need automake, pkg-config, gtk3, glib, libxml2, and libappindicator3 **along with their associated dev packages**. The configure script and makefiles are included in the tarball, so just run ./configure && make.

Try installing package `gtk3-devel-3.24.35` and see if you get any further.

**Comment by Ricky-Tigg** [comment]
It appeared that all package requirements were not met, were required:
```
$ dnf -q rq --installed --archlist noarch,x86_64 --qf '%{name} %{version}' \
automake pkgconf {gtk3,libappindicator-gtk3}{,-devel} glib2 libxml2 gcc intltool | column
automake 1.16.5			intltool 0.51.0
gcc 12.2.1			libappindicator-gtk3 12.10.1
glib2 2.74.1			libappindicator-gtk3-devel 12.10.1
gtk3 3.24.35			libxml2 2.10.3
gtk3-devel 3.24.35		pkgconf 1.8.0
```
Then _libappindicator_ and _gtk+_ were removed. At last all components were found. Warnings and errors occured –[gstm.txt](https://github.com/dallenwilson/gstm/files/10295916/gstm.txt); though they don't seem to me to be in my power to avoid.

**Comment by dallenwilson** [comment]
It looks like you're missing devel packages for glib and libxml2.

**Comment by Ricky-Tigg** [comment]
```
$ dnf -q rq --installed --qf '%{name} %{version}' {automake,libpkgconf,pkgconf,gtk3,glib2,libxml2,libappindicator,gcc,gtk+}{,-devel} util-linux{,-core} openssh-askpass | column
automake 1.16.5			libappindicator-devel 12.10.1
gcc 12.2.1			libpkgconf 1.8.0
glib2 2.74.1			libpkgconf-devel 1.8.0
glib2-devel 2.74.1		libxml2 2.10.3
gtk+ 1.2.10			libxml2-devel 2.10.3
gtk+-devel 1.2.10		openssh-askpass 8.8p1
gtk3 3.24.36			pkgconf 1.8.0
gtk3-devel 3.24.36		util-linux 2.38.1
libappindicator 12.10.1		util-linux-core 2.38.1
```
Using `openssh` , or a front-end for it, without relying on password for login is one of my requirements. However it appears that it is in your code defined as condition to be met. Nonetheless was installed `openssh-askpass` in order to meet that requirement.
```
$ ./autogen.sh && ./configure
checking whether we are cross compiling... no
checking for gcc option to enable C11 features... none needed
checking for app_indicator_new in -layatana-appindicator3... no
```
 I encounter errors when `make `operates.

**Comment by Ricky-Tigg** [comment]
```
$ dnf rq --installed --qf '%{name} %{version}' {automake,libpkgconf,pkgconf,gtk3,glib2,libxml2,libappindicator,gcc,gtk+}{,-devel} util-linux{,-core} openssh-askpass | column
automake 1.16.5			libappindicator-devel 12.10.1
gcc 12.2.1			libpkgconf 1.8.0
glib2 2.74.1			libpkgconf-devel 1.8.0
glib2-devel 2.74.1		libxml2 2.10.3
gtk+ 1.2.10			libxml2-devel 2.10.3
gtk+-devel 1.2.10		openssh-askpass 8.8p1
gtk3 3.24.36			pkgconf 1.8.0
gtk3-devel 3.24.36		util-linux 2.38.1
libappindicator 12.10.1		util-linux-core 2.38.1
```
Using `openssh` , or a front-end for it, without relying on password for login is one of my requirements. However it appears that it is in your code defined as condition to be met. Nonetheless was installed `openssh-askpass` in order to meet that requirement.
```
$ ./autogen.sh && ./configure
checking whether we are cross compiling... no
checking for gcc option to enable C11 features... none needed
checking for app_indicator_new in -layatana-appindicator3... no
```
 I encounter errors when `make `operates.

**Comment by dallenwilson** [comment]
An SSH_ASKPASS-compatible program is required if your ssh connection requires any input from you. Passwords, a passphrase for a key, etc. One is provided by gstm (gAskpass), though installing openssh-askpass is also a solution. If your tunnel is set up to use a key without a passphrase attached to it, you should not need an SSH_ASKPASS program.

You stated you encounter errors when running `make`, but you attached a section of the `./configure` script output. The output looks like it was generated by the current commit in the master branch, not the last release tarball.

Are you trying to build from the v1.3.7 release tarball, or the code in the master branch of the git repository?

**Comment by Ricky-Tigg** [comment]
Correct. It was generated by the code that is in _master_. To build upon that code was my attempt. New attempt, now upon the latest release tarball. The file _autogen.sh_ is not present, so i could omit the according invocation to it. Package _openssh-askpass_ removed.
```
$ ./configure | grep -E ' no$|needed$'
checking whether we are cross compiling... no
checking for gcc option to accept ISO C89... none needed
checking for CFPreferencesCopyAppValue... no
checking for CFLocaleCopyCurrent... no
checking for dlltool... no
checking for sysroot... no
checking for mt... no
checking if : is a manifest tool... no
checking if gcc supports -fno-rtti -fno-exceptions... no
checking if gcc static flag -static works... no
checking whether -lc should be explicitly linked in... no
```

**Comment by dallenwilson** [comment]
There is most definitely an `autogen.sh` file in every release tarball.

I suspect that I cannot help you with the issues you are having. Good luck.

**Comment by Ricky-Tigg** [comment]
At last on the right track. I had run against _gstm-1.3.7.tar.gz_ instead of _Source code (tar.gz)_. Errors reported | [autogen.sh_output.txt](https://github.com/dallenwilson/gstm/files/10931088/autogen.sh_output.txt). `./configure | grep -E ' no$|needed$'`'s output unchanged.
