### ISSUE TITLE
gaskpass window not displayed

### ISSUE THREAD

**Issue by hrotkogabor** [dallenwilson/gstm#4]
When I try to connect to a host (without port forward set), and I do not have ssh key, I get a window with this message when I click connect:

**Tunnel 'myTunnel' stopped
(gaskpass:20828): GLib-GIO-WARNING: your application claims to support opening files but does not implement g_application_open() and has no handlers connected to the 'open' signal.
user@host: Permission denied (publickey, password).**

When I apply this codechange in gaskpass.c:

```
static void
open (GApplication  *application,
      GFile        **files,
      gint           n_files,
      const gchar   *hint)
{
}

gAskpass * gaskpass_new (void)
{
  gAskpass * app = g_object_new (gaskpass_get_type(),
                       "application-id", "org.gtk.gaskpass",
                       "flags", G_APPLICATION_HANDLES_OPEN,
                       NULL);
  g_signal_connect (app, "open", G_CALLBACK (open), NULL);

  return app;
}
```

I get this message in a window after some seconds:
**"Tunnel 'myTunnel' stopped
user@host: Permission denied (publickey, password)."**

When I start gstm from cli, It will ask for the password there: "**user@host's password:**"
and entering the password, will connect successfully.

Gaskpass should work with gui.

Sysinfo:
Manjaro current with gtk3 3.24

**Comment by dallenwilson** [comment]
I will make some time this week and see what I can do.

**Comment by dallenwilson** [comment]
Found the problem, will have a fix shortly.

**Comment by dallenwilson** [comment]
Try a build from the 'gaskpass-bugfix' branch and see if it works for you.

**Comment by hrotkogabor** [comment]
Thanx! It is working now.
I have a note: when gaskpass window appear, it is filled with some unknown text, and all selected.
It is just a minor thing.
And a questions: Is it normal, that when I start gstm from the cli, it will ask for the password there, not in the gui window?

**Comment by dallenwilson** [comment]
gstm does not call gAskpass. It sets the SSH_ASKPASS env variable to 'gaskpass' if it is not already set to something else, and ssh handles opening and using whatever program is in the env variable. You can read about how SSH_ASKPASS is supposed to work in the [man page](https://man.openbsd.org/ssh#SSH_ASKPASS). Starting gstm from the cli and having the password requested in the cli is normal behavior, and explained in the man page.

gAskpass takes one command-line argument, a password to pre-fill the password window with. Whatever unknown text is there when it opens, is supplied by ssh when it opens it.

**Comment by hrotkogabor** [comment]
I debugged it, and the cli argument to gaskpass is this: "user@host's password:".
Is it make sense to set it to the label's text? Is there any case when it can be a real password?

**Comment by dallenwilson** [comment]
I checked another SSH_ASKPASS gui frontend ([x11-ssh-askpass](https://github.com/sigmavirus24/x11-ssh-askpass)) to see how things are supposed to work, and you're right. The initial argument supplied by SSH is intended to be a label, not a password. Thanks for the work troubleshooting this, I'll add a patch to correct how gAskpass handles it.
