### ISSUE TITLE
List of tunnels is not resized when window changes size.

### ISSUE THREAD

**Issue by xvybihal** [dallenwilson/gstm#7]
When I resize window, the list does not reflect that and keeps it's fixed size. The Gtk2 version did not do this. Would it be possible to fix it? And a subrequest, could it remember the window size so we do not have to resize it every time we run GSTM? :)

![Screenshot_2019-09-06_08-57-09](https://user-images.githubusercontent.com/3757613/64407514-c4f28780-d084-11e9-9073-04e859657c78.png)

**Comment by dallenwilson** [comment]
I imagine it is possible to fix it, yes. I'll take a look this week.

**Comment by dallenwilson** [comment]
Try a build from the latest master branch commit, the tunnel list should now resize properly.

Remembering previous window size is also do-able, I'll try to get that done this week.

**Comment by xvybihal** [comment]
Thanks for quick response. Now resize works as expected.
I have created gstm-git package to [AUR](https://aur.archlinux.org/packages/gstm-git/).
