### ISSUE TITLE
gstm on ubuntu does show green button (no failure message)even when it failed to ssh to a server

### ISSUE THREAD

**Issue by lav-patel** [dallenwilson/gstm#8]
gstm on ubuntu 18.04 does show green button (no failure message)even when it failed to ssh to a server

I wish it shows failure when there is a failure and even better it shows ssh command it uses to connect and what is the exact error message.

**Comment by dallenwilson** [comment]
The status icon will always turn green when a tunnel is started, and it won't turn red until ssh returns with a failure message, which is displayed in a pop-up window. The only way I can think of for no message to be displayed is if the ssh child process hangs or dies without exiting properly. Even then, gstm should catch the kill notice and change the icon. Can you confirm that an ssh child process is being launched, and if it's still running? Perhaps using `ps -A | grep ssh`

I won't have access to an ubuntu 18.04 machine until the end of the month, but if you can provide some more information maybe I can help you before then. Can you connect to your server without using gstm? Are you using password or public key authentication? Are you using a build from the ppa, or one compiled yourself from the source here on github?

**Comment by lav-patel** [comment]
I was able to fix my error, I was using wrong username, but I wish it was easier to know something went wrong rather than thinking tunnel is on (green button). I never recieved a failure message (which is displayed in a pop-up window). I waited for 2 min, may be I should have waited more. 

after starting a  tunnel with green color (with wrong username)
```
ps -ef|grep ssh
root      1401     1  0 Feb12 ?        00:00:00 /usr/sbin/sshd -D
username   16140 15699  0 15:20 tty2     00:00:00 ssh SERVERNAME -p 22 -l username -nN -L1521:localhost:1521 -D8397 -o ConnectTimeout=5 -o NumberOfPasswordPrompts=1
username   16143 16044  0 15:20 pts/0    00:00:00 grep --color=auto ssh
username   25751 22861  0 09:30 ?        00:00:00 /usr/bin/ssh-agent -D -a /run/user/1000/keyring/.ssh
```
```
ps -A | grep ssh
 1401 ?        00:00:00 sshd
16140 tty2     00:00:00 ssh
25751 ?        00:00:00 ssh-agent
```

**Comment by dallenwilson** [comment]
Glad to hear you got your tunnel working.

**Comment by dallenwilson** [comment]
I did find something that will cause a tunnel to hang, leaving the icon green and generating no error message: Connecting to a new server that supports pubkey authentication. SSH will display the server key in the terminal window and ask the user to verify the authenticity of it before proceeding, and gstm has no way of knowing that happened.

I'll update the readme and possibly add a note in the program reminding users to verify the connection works with SSH before trying to set up a tunnel.

**Comment by lav-patel** [comment]
Sorry for late reply , Now it shows me error, but no option to enter the password, if i dont have key


![image](https://user-images.githubusercontent.com/8277466/78451904-cc473700-764d-11ea-8710-c89d92682b2b.png)

**Comment by lav-patel** [comment]
This answer should help fixing src code.

https://unix.stackexchange.com/questions/83986/tell-ssh-to-use-a-graphical-prompt-for-key-passphrase/83991#83991
