### ISSUE TITLE
allow user to authenticate through password

### ISSUE THREAD

**Issue by lav-patel** [dallenwilson/gstm#9]
I can authenticate through private key, but I would like to authenticate as password for some other server.

**Comment by dallenwilson** [comment]
I do not understand the problem. Gstm already supports password authentication.

**Comment by lav-patel** [comment]
ohh..sorrry I might have missed it. can you tell me how?

![image](https://user-images.githubusercontent.com/8277466/75361097-644a4780-587c-11ea-9d3a-ef942da60c84.png)

**Comment by dallenwilson** [comment]
Authentication is handled by ssh, there are no settings for it in gstm. If ssh decides the username and server you've entered in the gstm tunnel configuration require a password, it will open a pop-up to ask you for one. Other than providing a compatible program to be used as a pop-up (in case your system does not have one; Most do not), gstm doesn't get involved at all.

If you're trying to override default behavior, try editing your ssh config in `~/.ssh/config` or the system-wide file at `/etc/ssh/ssh_config`.

I've created a short video to [show how things are supposed to work](https://www.youtube.com/watch?v=SHIzRsLloD8&feature=youtu.be). If you're not getting password prompts or ssh errors in pop-up windows, then something is clearly wrong and we should try to find out what.

**Comment by lav-patel** [comment]
yes I don not get password prompt. I am using (ubuntu 18.04.4 LTS)
>If you're not getting password prompts or ssh errors in pop-up windows, then something is clearly wrong and we should try to find out what.

```
 cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.4 LTS"
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

**Comment by dallenwilson** [comment]
I installed Ubuntu 18.04 with the standard Unity desktop, and no password prompt is being displayed. Error messages do show as pop-ups, though. I'll see if I can fix it.

**Comment by dallenwilson** [comment]
Edit `/usr/share/applications/gstm.desktop` and change `Exec=gstm` to `Exec=setsid gstm`. That should fix the password prompt issue. I noticed a few other things that need correcting, so it will be a few days before a new version is released with that fix in it.

**Comment by dallenwilson** [comment]
The setsid fix in gstm.desktop has been commited to the repo, along with several other UI improvements and minor bugfixes. Try building from the latest commit and let me know how it goes for you.

**Comment by lav-patel** [comment]
Thanks for fixing. Let me see if I can spin up dev machine for testing. Thanks

**Comment by dallenwilson** [comment]
Did it resolve the problem for you?

**Comment by dallenwilson** [comment]
Closing due to lack of response and assuming issue is resolved.

**Comment by lav-patel** [comment]
Sorry for late reply , Now it shows me error, but no option to enter the password, if i don't have key


![image](https://user-images.githubusercontent.com/8277466/78451904-cc473700-764d-11ea-8710-c89d92682b2b.png)

**Comment by lav-patel** [comment]
This answer should help fixing src code.

https://unix.stackexchange.com/questions/83986/tell-ssh-to-use-a-graphical-prompt-for-key-passphrase/83991#83991

**Comment by dallenwilson** [comment]
The source code isn't broken, and gstm is already making use of SSH_ASKPASS. It has done so since 2006.

The gtk errors are my fault, I forgot to update a Makefile when I changed gAskpass's UI code. I'll attend to that now.

The root of your specific problem is shown by the last line of that error message: Host key verification failed.

**Comment by dallenwilson** [comment]
v1.3.6 is released and correctly installs the gaskpass.ui file, so gAskpass should work again. It'll be available for bionic from the Launchpad PPA shortly. Give it a try.

**Comment by lav-patel** [comment]
awesome job! this fixed the issue.
